name: Sensitive Content Scanner

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: windyinwind/sensitive-scanner-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sensitive-words-file: '.github/sensitive-words.txt' 
          fail-on-detection: false
